name: roademics
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.0
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  cached_network_image: ^3.4.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-VariableFont_wght.ttf
      
  assets:
        - assets/img/home.png
        - assets/img/notifications.png
        - assets/img/opportunities.png
        - assets/img/profile.png
        - assets/img/roadmaps.png